/* ----------------------------------------------------------------
   KVIFF 60 — statická data
   Program 8.–11. 7. 2026, zdroj: kviff.com
---------------------------------------------------------------- */

export const SECTIONS = {
  HS:   { name: "Hlavní soutěž",               color: "#E8A33D" },
  HOR:  { name: "Horizonty",                   color: "#6BA3C4" },
  PROX: { name: "Soutěž Proxima",              color: "#9B8BD0" },
  ZU:   { name: "Zvláštní uvedení",            color: "#5FB3A1" },
  ZUC:  { name: "Zvláštní uvedení – Classics", color: "#4E8C7E" },
  NAV:  { name: "Návraty k pramenům",          color: "#C77D55" },
  IMA:  { name: "Imagina",                     color: "#C46BA0" },
  POZ:  { name: "Po zavíračce",                color: "#B0506A" },
  POC:  { name: "Pocty",                       color: "#C9A24B" },
  KRAT: { name: "Krátké filmy / pásmo",        color: "#8A8276" },
  AKCE: { name: "Doprovodný program",          color: "#D98C6A" },
};

// pos = orientační min pěšky od Thermalu; lat/lng = reálné souřadnice
export const VENUES = {
  T1:   { name: "Velký sál",        short: "Velký",      sub: "Thermal",      pos: 0,  grp: "T", lat: 50.228820, lng: 12.876514 },
  T2:   { name: "Malý sál",         short: "Malý",       sub: "Thermal",      pos: 0,  grp: "T", lat: 50.228820, lng: 12.876514 },
  T3:   { name: "Kongresový sál",   short: "Kongres.",   sub: "Thermal",      pos: 0,  grp: "T", lat: 50.228820, lng: 12.876514 },
  T4:   { name: "Kinosál B",        short: "Kino B",     sub: "Thermal",      pos: 0,  grp: "T", lat: 50.228820, lng: 12.876514 },
  CAS:  { name: "Kino Čas",         short: "Čas",        sub: "u Thermalu",   pos: 6,  grp: "",  lat: 50.228450, lng: 12.874050 },
  DRA:  { name: "Kino Drahomíra",   short: "Drahomíra",  sub: "Drahovice",    pos: 9,  grp: "",  lat: 50.235125, lng: 12.878739 },
  HUS:  { name: "Divadlo Husovka",  short: "Husovka",    sub: "",             pos: 11, grp: "",  lat: 50.219936, lng: 12.880688 },
  MD:   { name: "Městské divadlo",  short: "Měst. div.", sub: "",             pos: 13, grp: "",  lat: 50.221094, lng: 12.881629 },
  L3:   { name: "Lázně III",        short: "Lázně III",  sub: "",             pos: 15, grp: "",  lat: 50.226723, lng: 12.879815 },
  CIS:  { name: "Císařské lázně",   short: "Cís. lázně", sub: "",             pos: 18, grp: "",  lat: 50.218963, lng: 12.881530 },
  PUPP: { name: "Pupp",             short: "Pupp",       sub: "Grandhotel",   pos: 22, grp: "",  lat: 50.219756, lng: 12.878532 },
};

// cat: rest|pizza|bistro|cafe|bar|spring|atm|pharm · o/c = od/do (h, c>24 = po půlnoci)
export const PLACES = [
  { n:"Plzeňská Restaurace Palacký", la:50.221354, ln:12.880302, cat:"rest",   tag:"Česká kuchyně, zahrádka",          o:10,   c:22, price:2 },
  { n:"Restaurant Romance",          la:50.223492, ln:12.882504, cat:"rest",   tag:"Česká klasika u kolonády",         o:7.5,  c:21, price:2 },
  { n:"Goethe's Beer House",         la:50.221959, ln:12.881517, cat:"rest",   tag:"Pivnice + jídlo, Stará Louka",     o:12,   c:23, price:2 },
  { n:"Restaurace Sklípek",          la:50.229091, ln:12.869238, cat:"rest",   tag:"Levná česká, jen hotovost",        o:11,   c:22, price:1 },
  { n:"Staroslovanská kuchyně",      la:50.228838, ln:12.867604, cat:"rest",   tag:"Velké porce u Thermalu",           o:11,   c:21, price:2 },
  { n:"La Hospoda",                  la:50.233050, ln:12.871813, cat:"rest",   tag:"Oblíbená česká, rezervovat",       o:11,   c:22, price:2 },
  { n:"Pizzeria La Famiglia",        la:50.221443, ln:12.880674, cat:"pizza",  tag:"Italská, Stará Louka",             o:12,   c:23, price:2 },
  { n:"Pizzeria Sorriso",            la:50.228769, ln:12.866884, cat:"pizza",  tag:"Tenká pizza, jen večer",           o:17,   c:21, price:2 },
  { n:"New York Burger",             la:50.229209, ln:12.871788, cat:"bistro", tag:"Burgery, otevřeno dlouho",         o:9,    c:23, price:2 },
  { n:"Streetfood",                  la:50.223529, ln:12.882527, cat:"bistro", tag:"Rychlé jídlo u kolonády",          o:12,   c:21, price:1 },
  { n:"Café Elefant",                la:50.221644, ln:12.881057, cat:"cafe",   tag:"Historická kavárna, terasa",       o:9,    c:21, price:2 },
  { n:"Raposa Coffee",               la:50.220547, ln:12.883962, cat:"cafe",   tag:"Specialty káva, blízko Puppu",     o:9,    c:19, price:2 },
  { n:"Republica coffee",            la:50.230038, ln:12.869071, cat:"cafe",   tag:"Brunch + káva u Thermalu",         o:8,    c:18, price:2 },
  { n:"Pinkiez espresso bar",        la:50.229416, ln:12.868268, cat:"cafe",   tag:"KVIFF oblíbenec, hip-hop vibe",    o:7,    c:18, price:1 },
  { n:"Kavárna Nebe",                la:50.229198, ln:12.870220, cat:"cafe",   tag:"Klidná kavárna u Thermalu",        o:8,    c:18, price:1 },
  { n:"Becher's Bar",                la:50.219580, ln:12.879312, cat:"bar",    tag:"Špičkové koktejly v Puppu",        o:19,   c:26, price:3 },
  { n:"Barracuda Cocktail Bar",      la:50.229289, ln:12.867676, cat:"bar",    tag:"Tiki bar, jen pá–ne, tanec",       o:19,   c:26, price:2 },
  { n:"Craft Beer Point",            la:50.230075, ln:12.868849, cat:"bar",    tag:"Craft piva u Thermalu",            o:16,   c:24, price:2 },
  { n:"Beer & Láska",                la:50.228805, ln:12.869173, cat:"bar",    tag:"Pivotéka, čepované speciály",      o:13.5, c:19, price:2 },
  { n:"Pivnice Drahomíra",           la:50.235296, ln:12.882564, cat:"bar",    tag:"Hospoda u kina Drahomíra",         o:15,   c:24, price:1 },
  { n:"Slash Bar",                   la:50.238425, ln:12.877812, cat:"bar",    tag:"Rock klub, živá hudba",            o:17,   c:24, price:2 },
  { n:"Vřídelní kolonáda (pramen)",  la:50.222712, ln:12.883365, cat:"spring", tag:"Nejteplejší pramen, voda",         o:7,    c:19, price:0 },
  { n:"Mlýnská kolonáda (prameny)",  la:50.225287, ln:12.881781, cat:"spring", tag:"Prameny, voda zdarma",             o:0,    c:24, price:0 },
  { n:"Fio bankomat (bez poplatku)", la:50.230244, ln:12.868146, cat:"atm",    tag:"Výběr bez poplatku, 24/7",         o:0,    c:24, price:0 },
  { n:"Euronet ATM Stará Louka",     la:50.222406, ln:12.882189, cat:"atm",    tag:"Bankomat 24/7 (poplatek)",         o:0,    c:24, price:0 },
  { n:"Lékárna St. Maria",           la:50.224577, ln:12.882245, cat:"pharm",  tag:"Lékárna, centrum",                 o:9,    c:19, price:0 },
];

export const CAT = {
  rest:   { l:"Restaurace",       e:"🍽️", g:"jídlo" },
  pizza:  { l:"Pizza",            e:"🍕",  g:"jídlo" },
  bistro: { l:"Bistro / rychlé",  e:"🥪",  g:"jídlo" },
  cafe:   { l:"Kavárna",          e:"☕",  g:"pití"  },
  bar:    { l:"Bar / pivo",       e:"🍺",  g:"pití"  },
  spring: { l:"Pramen / voda",    e:"💧",  g:"praktické" },
  atm:    { l:"Bankomat",         e:"🏧",  g:"praktické" },
  pharm:  { l:"Lékárna",          e:"💊",  g:"praktické" },
};

export const EVENTS = [
  { id:"E8a",  day:8,  t:"15:00", v:"T1",   title:"KVIFF Talk: herecký host",          cat:"talk",  r:60  },
  { id:"E8b",  day:8,  t:"21:30", v:"T1",   title:"Open-air projekce u Thermalu",      cat:"open",  r:120 },
  { id:"E8c",  day:8,  t:"23:00", v:"PUPP", title:"Párty — Becher's Bar",              cat:"party", r:180 },
  { id:"E9a",  day:9,  t:"17:00", v:"L3",   title:"Koncert na Mlýnské kolonádě",       cat:"music", r:75  },
  { id:"E9b",  day:9,  t:"21:30", v:"T1",   title:"Open-air projekce u Thermalu",      cat:"open",  r:120 },
  { id:"E9c",  day:9,  t:"23:30", v:"T1",   title:"DJ párty u Thermalu",               cat:"party", r:210 },
  { id:"E10a", day:10, t:"15:00", v:"T1",   title:"KVIFF Talk: režisérský host",       cat:"talk",  r:60  },
  { id:"E10b", day:10, t:"21:30", v:"T1",   title:"Open-air projekce u Thermalu",      cat:"open",  r:120 },
  { id:"E10c", day:10, t:"23:30", v:"DRA",  title:"After-party — Slash Bar",           cat:"party", r:180 },
  { id:"E11a", day:11, t:"20:00", v:"T1",   title:"Slavnostní zakončení festivalu",    cat:"cer",   r:90  },
  { id:"E11b", day:11, t:"23:00", v:"T1",   title:"Závěrečná párty",                   cat:"party", r:210 },
];
export const EVENT_EMOJI = { talk:"🎙️", open:"🌙", party:"🎉", music:"🎵", cer:"🏆" };
export const EVById = Object.fromEntries(EVENTS.map(e => [e.id, e]));

export const BADGE_LABELS = { must:"Tahák", cine:"Pro cinefily", classic:"Klasika", night:"Noční" };

// Naše výběry z přípravky — yes = tučně v PDF (must see), maybe = ???, sary = ŠÁRY VARY (lze vidět i po)
export const PICKS = {
  // Chceme — tučně zvýrazněné v PDF
  "50644":"yes","49419":"yes","50262":"yes","49934":"yes","50666":"yes",
  "50659":"yes","49697":"yes","49174":"yes","50663":"yes","50651":"yes",
  "50664":"yes","49679":"yes","50629":"yes","50535":"yes","49418":"yes",
  "49696":"yes","50692":"yes",
  // Možná — označené ???
  "50667":"maybe","50653":"maybe","50634":"maybe","48467":"maybe","50660":"maybe",
  "49467":"maybe","50251":"maybe","50526":"maybe","50528":"maybe","50602":"maybe",
  "48448":"maybe","50536":"maybe","50630":"maybe","49425":"maybe",
  // Šáry vary — ŠARY VARY v PDF, ale ne tučné
  "50662":"sary","48780":"sary","49760":"sary","50513":"sary","49310":"sary",
};

export const TICKET = {
  want: { i:"◷",   l:"chci",      c:"#E8A33D" },
  have: { i:"🎟️", l:"mám",       c:"#6FB36F" },
  sold: { i:"⊘",   l:"vyprodáno", c:"#E06A4E" },
};

// [t]itul, [d]režie, [c]země, [y]rok, [r]délka(min), [s]ekce, [b]adge, syn, [u]slug
export const FILMS = {
  "50433": { t:"Kes",                                           d:"Ken Loach",                              c:"Velká Británie",                    y:1969, r:111, s:"NAV",  b:"classic", syn:"Chlapec z hornického Yorkshiru najde únik z drsného života ve výcviku poštolky. Klenot britské sociální nové vlny.",              u:"50433-kes" },
  "49480": { t:"Kdyby se holubi proměnili ve zlato",            d:"Pepa Lubojacki",                         c:"ČR, SK",                            y:2026, r:110, s:"ZU",   b:"",        syn:"",                                                                                                                              u:"49480-kdyby-se-holubi-promenili-ve-zlato" },
  "50666": { t:"Papírový tygr",                                 d:"James Gray",                             c:"USA",                               y:2026, r:115, s:"HOR",  b:"must",    syn:"Nový film Jamese Graye (Armageddon Time, Ztracené město Z).",                                                                    u:"50666-papirovy-tygr" },
  "49965": { t:"Potrubí",                                       d:"Karim Kassem",                           c:"Libanon, Katar, SA",                y:2025, r:112, s:"HS",   b:"",        syn:"",                                                                                                                              u:"49965-potrubi" },
  "50526": { t:"Hidžamat",                                      d:"Nader Saeivar",                          c:"Německo",                           y:2026, r:103, s:"HS",   b:"",        syn:"Politicky laděné drama od spolupracovníka Jafara Panahiho.",                                                                     u:"50526-hidzamat" },
  "49702": { t:"The Moment",                                    d:"Aidan Zamiri",                           c:"USA",                               y:2026, r:103, s:"POZ",  b:"night",   syn:"Pulzující mockument o popové ikoně Charli XCX.",                                                                                 u:"49702-the-moment" },
  "50659": { t:"La gradiva",                                    d:"Marine Atlan",                           c:"Francie, Itálie",                   y:2026, r:145, s:"HOR",  b:"cine",    syn:"",                                                                                                                              u:"50659-la-gradiva" },
  "50601": { t:"Dvě deci tuše",                                 d:"Ester Geislerová",                       c:"ČR, SK",                            y:2026, r:83,  s:"ZU",   b:"",        syn:"",                                                                                                                              u:"50601-dve-deci-tuse" },
  "49309": { t:"Zpráva pro Minervu 2",                          d:"Miroslav Krobot, Lubomír Smékal",        c:"ČR",                                y:2026, r:68,  s:"ZU",   b:"",        syn:"",                                                                                                                              u:"49309-zprava-pro-minervu2" },
  "50599": { t:"Igor a potom",                                  d:"Ivan Ostrochovský",                      c:"SK, ČR",                            y:2026, r:70,  s:"ZUC",  b:"",        syn:"",                                                                                                                              u:"50599-igor-apotom" },
  "49676": { t:"Everybody Digs Bill Evans",                     d:"Grant Gee",                              c:"Irsko, VB",                         y:2026, r:103, s:"HOR",  b:"cine",    syn:"Hudební dokument o legendárním jazzovém pianistovi Billu Evansovi.",                                                             u:"49676-everybody-digs-bill-evans" },
  "50602": { t:"Jim Queen",                                     d:"Marco Nguyen, Nicolas Athane",           c:"Francie, Belgie",                   y:2026, r:84,  s:"POZ",  b:"night",   syn:"",                                                                                                                              u:"50602-jim-queen" },
  "50262": { t:"Nečekaný host",                                 d:"Mads Mengel",                            c:"Dánsko",                            y:2026, r:100, s:"HS",   b:"",        syn:"",                                                                                                                              u:"50262-necekany-host" },
  "49760": { t:"Pramen",                                        d:"Ivan Ostrochovský",                      c:"SK, ČR, HU",                        y:2026, r:88,  s:"HS",   b:"must",    syn:"Drama zasazené do poloviny 80. let od autora oceňovaných Služebníků.",                                                          u:"49760-pramen" },
  "50430": { t:"Obžalovaný",                                    d:"Ján Kadár, Elmar Klos",                  c:"Československo",                    y:1964, r:94,  s:"NAV",  b:"classic", syn:"Od pozdějších oscarových tvůrců Obchodu na korze.",                                                                             u:"50430-obzalovany" },
  "50426": { t:"Kapitán Blesk",                                 d:"Cecil Holmes",                           c:"Austrálie",                         y:1952, r:73,  s:"NAV",  b:"classic", syn:"Vzácná australská klasika o legendárním banditovi.",                                                                             u:"50426-kapitan-blesk" },
  "50357": { t:"Morten",                                        d:"Ivan Pavljutskov",                       c:"Estonsko, Litva",                   y:2026, r:101, s:"ZU",   b:"",        syn:"",                                                                                                                              u:"50357-morten" },
  "49419": { t:"Zlodějíčci",                                    d:"Mate Ugrin",                             c:"Chorvatsko, FR, DE, RS",            y:2026, r:110, s:"PROX", b:"",        syn:"",                                                                                                                              u:"49419-zlodejicci" },
  "49467": { t:"Člověk skoro celý",                             d:"Efthimis Kosemund-Sanidis",              c:"Řecko, BG, DE, CY, RO",             y:2025, r:112, s:"PROX", b:"",        syn:"",                                                                                                                              u:"49467-clovek-skoro-cely" },
  "50432": { t:"Chladné dny",                                   d:"András Kovács",                          c:"Maďarsko",                          y:1966, r:101, s:"NAV",  b:"classic", syn:"Čtyři důstojníci vzpomínají na masakr v Novém Sadu 1942.",                                                                       u:"50432-chladne-dny" },
  "48448": { t:"Podivná řeka",                                  d:"Jaume Claret Muxart",                    c:"Španělsko, Německo",                y:2025, r:106, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"48448-podivna-reka" },
  "49697": { t:"Animol",                                        d:"Ashley Walters",                         c:"Velká Británie",                    y:2026, r:93,  s:"HOR",  b:"",        syn:"",                                                                                                                              u:"49697-animol" },
  "49680": { t:"Má žena pláče",                                 d:"Angela Schanelec",                       c:"Německo, Francie",                  y:2026, r:93,  s:"IMA",  b:"cine",    syn:"Nový film Angely Schanelec (berlínská škola). Náročná forma.",                                                                   u:"49680-ma-zena-place" },
  "49183": { t:"Paříž Paříž",                                   d:"Isabelle Tollenaere",                    c:"Belgie",                            y:2026, r:79,  s:"PROX", b:"",        syn:"",                                                                                                                              u:"49183-pariz-pariz" },
  "49047": { t:"Můj kamarád pornohvězda",                       d:"Rosa Friedrich",                         c:"Rakousko",                          y:2026, r:95,  s:"PROX", b:"",        syn:"",                                                                                                                              u:"49047-muj-kamarad-pornohvezda" },
  "49174": { t:"Krásný smutný svět",                            d:"Cyril Aris",                             c:"Libanon, USA, DE, SA",              y:2025, r:110, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"49174-krasny-smutny-svet" },
  "50633": { t:"Kolonie",                                       d:"Sang-ho Yeon",                           c:"Jižní Korea",                       y:2026, r:123, s:"POZ",  b:"night",   syn:"Jihokorejský zombie film od režiséra Vlaku do Busanu.",                                                                          u:"50633-kolonie" },
  "50337": { t:"Město otců",                                    d:"Zdeněk Tyc",                             c:"ČR, SK, PL",                        y:2026, r:100, s:"ZU",   b:"",        syn:"",                                                                                                                              u:"50337-mesto-otcu" },
  "50111": { t:"Jak se naučit dýchat pod vodou",                d:"Rebekah Fortune",                        c:"Irsko, VB, NL",                     y:2026, r:96,  s:"ZU",   b:"",        syn:"Britsko-irský rodinný film.",                                                                                                    u:"50111-jak-se-naucit-dychat-pod-vodou" },
  "50065": { t:"Kamioňáci",                                     d:"Francisco Marise",                       c:"Španělsko, Argentina",              y:2025, r:85,  s:"PROX", b:"",        syn:"",                                                                                                                              u:"50065-kamionaci" },
  "50038": { t:"Spalovna",                                      d:"Shuntaro Uchida",                        c:"Japonsko",                          y:2026, r:98,  s:"PROX", b:"",        syn:"",                                                                                                                              u:"50038-spalovna" },
  "50663": { t:"Hořké svátky",                                  d:"Pedro Almodóvar",                        c:"Španělsko",                         y:2026, r:113, s:"HOR",  b:"must",    syn:"Nový film Pedra Almodóvara.",                                                                                                    u:"50663-horke-svatky" },
  "48447": { t:"Tichá přítelkyně",                              d:"Ildikó Enyedi",                          c:"Německo, HU, FR",                   y:2025, r:148, s:"HOR",  b:"must",    syn:"Od držitelky Zlatého medvěda Ildikó Enyedi (Tělo a duše).",                                                                      u:"48447-ticha-pritelkyne" },
  "50647": { t:"Dvojitá svoboda",                               d:"Lisandro Alonso",                        c:"Chile, AR, LU, DE, VB",             y:2026, r:101, s:"IMA",  b:"cine",    syn:"Nový film Lisandra Alonsa (Jauja, Eureka). Pomalé art-house.",                                                                   u:"50647-dvojita-svoboda" },
  "50435": { t:"Vesnický příběh",                               d:"Mrinal Sen",                             c:"Indie",                             y:1977, r:116, s:"NAV",  b:"classic", syn:"Klasika indického art filmu o venkovské chudobě.",                                                                               u:"50435-vesnicky-pribeh" },
  "49670": { t:"Opojení lesem",                                 d:"Manon Coubia",                           c:"Belgie, Francie",                   y:2026, r:102, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"49670-opojeni-lesem" },
  "48920": { t:"Vertigo Kim Novak",                             d:"Alexandre O. Philippe",                  c:"USA",                               y:2025, r:77,  s:"HOR",  b:"cine",    syn:"Filmová esej o Kim Novak a hitchcockovském Vertigu.",                                                                            u:"48920-vertigo-kim-novak" },
  "50429": { t:"Barravento",                                    d:"Glauber Rocha",                          c:"Brazílie",                          y:1962, r:81,  s:"NAV",  b:"classic", syn:"Debut zakladatele brazilského Cinema Novo.",                                                                                     u:"50429-barravento" },
  "50637": { t:"Vysněné dobrodružství",                         d:"Valeska Grisebach",                      c:"DE, FR, BG, AT",                    y:2026, r:167, s:"HOR",  b:"cine",    syn:"Od autorky oceňovaného Westernu. Dlouhých 167 min.",                                                                             u:"50637-vysnene-dobrodruzstvi" },
  "50646": { t:"Nácvik revoluce",                               d:"Pegah Ahangarani",                       c:"ČR, Španělsko",                     y:2026, r:98,  s:"HOR",  b:"",        syn:"",                                                                                                                              u:"50646-nacvik-revoluce" },
  "50323": { t:"Robert Richardson: The White Devil",            d:"Jana Hojdová",                           c:"ČR, USA",                           y:2026, r:105, s:"ZU",   b:"cine",    syn:"Dokument o slavném kameramanovi (Scorsese, Tarantino).",                                                                         u:"50323-robert-richardson-the-white-devil" },
  "50509": { t:"Rain Catcher",                                  d:"Michele Fiascaris",                      c:"Velká Británie",                    y:2026, r:110, s:"PROX", b:"",        syn:"",                                                                                                                              u:"50509-rain-catcher" },
  "48780": { t:"Milovník, ne bojovník",                         d:"Martina Buchelová",                      c:"SK, ČR",                            y:2026, r:109, s:"PROX", b:"",        syn:"Slovenský debut o létě, lásce a plánech, které rozhodí city.",                                                                  u:"48780-milovnik-nebojovnik" },
  "50251": { t:"Bílé noci, černý prachy",                       d:"Kristina Grozeva, Petar Valchanov",      c:"Bulharsko, Řecko",                  y:2026, r:95,  s:"HS",   b:"must",    syn:"Pár ušetří na cestu do Petrohradu; po ruské invazi o úspory přijdou podvodem. Od držitelů Křišťálového glóbu 2019.",           u:"50251-bile-noci-cerny-prachy" },
  "49934": { t:"Za zády mi číhá lev",                           d:"Tonia Mishiali",                         c:"Kypr, LU, Řecko",                   y:2026, r:106, s:"HS",   b:"must",    syn:"Senegalská žadatelka o azyl a uzavřená čtyřicátnice najdou nečekané pouto.",                                                    u:"49934-za-zady-mi-ciha-lev" },
  "50651": { t:"Něžné monstrum",                                d:"Marie Kreutzer",                         c:"AT, DE, FR, SE",                    y:2026, r:116, s:"HOR",  b:"must",    syn:"Od autorky oceňované Korzety (Corsage).",                                                                                        u:"50651-nezne-monstrum" },
  "49871": { t:"Pět let a čtyři měsíce",                        d:"Esteban Hoyos García, Juan Miguel Gelacio", c:"Kolumbie, USA",                  y:2025, r:84,  s:"HS",   b:"",        syn:"",                                                                                                                              u:"49871-pet-let-actyri-mesice" },
  "50402": { t:"Tři týdny poté",                                d:"Miroslav Terzić",                        c:"Srbsko, BG, IT, HR, LU",            y:2026, r:96,  s:"HS",   b:"must",    syn:"Třída uvázne v odlehlém horském hotelu; tichý student promluví o sebevraždě kamaráda.",                                         u:"50402-tri-tydny-pote" },
  "50600": { t:"Zavěšení Stuarta Cornfelda",                    d:"Joan Bofill Amargós",                    c:"USA, Španělsko",                    y:2025, r:90,  s:"ZUC",  b:"",        syn:"",                                                                                                                              u:"50600-zaveseni-stuarta-cornfelda" },
  "49310": { t:"Mistryně",                                      d:"Bohdan Karásek",                         c:"ČR",                                y:2026, r:101, s:"ZU",   b:"",        syn:"Nový český film B. Karáska (Karel, já a ty).",                                                                                   u:"49310-mistryne" },
  "50656": { t:"Zápas století",                                  d:"Juan Cabral, Santiago Franco",           c:"Argentina, Španělsko",              y:2026, r:91,  s:"HOR",  b:"",        syn:"",                                                                                                                              u:"50656-zapas-stoleti" },
  "50635": { t:"Domovina",                                      d:"Paweł Pawlikowski",                      c:"PL, DE, IT, FR",                    y:2026, r:82,  s:"HOR",  b:"must",    syn:"Nový film Pawła Pawlikowského (Ida, Studená válka).",                                                                            u:"50635-domovina" },
  "50664": { t:"Fjord",                                         d:"Cristian Mungiu",                        c:"RO, FR, NO, SE, DK",                y:2026, r:149, s:"HOR",  b:"must",    syn:"Nové drama Cristiana Mungiua (4 měsíce, 3 týdny a 2 dny).",                                                                     u:"50664-fjord" },
  "50683": { t:"V nás",                                         d:"Juliette Binoche",                       c:"Francie",                           y:2025, r:125, s:"POC",  b:"must",    syn:"Režijní počin Juliette Binoche.",                                                                                               u:"50683-v-nas" },
  "50528": { t:"Za deštěm",                                     d:"Valeria Sarmiento",                      c:"Chile",                             y:2026, r:98,  s:"HS",   b:"",        syn:"",                                                                                                                              u:"50528-za-destem" },
  "50539": { t:"Padlé ovoce",                                   d:"Aung Phyoe",                             c:"Myanmar, ČR, FR",                   y:2026, r:97,  s:"HS",   b:"",        syn:"",                                                                                                                              u:"50539-padle-ovoce" },
  "50634": { t:"Sex a smrt v kempu Miasma",                     d:"Jane Schoenbrun",                        c:"USA, Kanada",                       y:2026, r:112, s:"POZ",  b:"night",   syn:"Feministický slasher.",                                                                                                          u:"50634-sex-asmrt-vkempu-miasma" },
  "50513": { t:"Napořád",                                       d:"Sandra Wollner",                         c:"Rakousko, Německo",                 y:2026, r:124, s:"HOR",  b:"cine",    syn:"",                                                                                                                              u:"50513-naporad" },
  "50453": { t:"Ruka od inkoustu a chybějící palec",            d:"Yashasvi Juyal",                         c:"Indie, USA, SA",                    y:2026, r:127, s:"PROX", b:"",        syn:"",                                                                                                                              u:"50453-ruka-odinkoustu-achybejici-palec" },
  "49592": { t:"Proti přírodě",                                 d:"Axel Bertha",                            c:"Mexiko",                            y:2026, r:88,  s:"PROX", b:"",        syn:"",                                                                                                                              u:"49592-proti-prirode" },
  "50641": { t:"Neznámá",                                       d:"Arthur Harari",                          c:"Francie, Itálie",                   y:2026, r:139, s:"HOR",  b:"must",    syn:"Od Arthura Harariho (spoluautor scénáře Anatomie pádu, režisér Onoda).",                                                        u:"50641-neznama" },
  "49683": { t:"Zrozen z temnoty",                              d:"Hanna Bergholm",                         c:"FI, FR, VB, LT",                    y:2026, r:92,  s:"POZ",  b:"night",   syn:"",                                                                                                                              u:"49683-zrozen-ztemnoty" },
  "50532": { t:"Dějiny betonu",                                 d:"John Wilson",                            c:"USA",                               y:2026, r:102, s:"HOR",  b:"cine",    syn:"Od tvůrce kultovního How To with John Wilson.",                                                                                  u:"50532-dejiny-betonu" },
  "49844": { t:"Tajemství džungle",                             d:"Edmunds Jansons",                        c:"Lotyšsko, PL, ČR",                  y:2025, r:73,  s:"HOR",  b:"",        syn:"Animovaný rodinný film.",                                                                                                        u:"49844-tajemstvi-dzungle" },
  "49907": { t:"Zemřít za život",                               d:"Yuliia Hontaruk",                        c:"Ukrajina, LV, SK",                  y:2026, r:116, s:"ZU",   b:"",        syn:"Ukrajinský dokument.",                                                                                                           u:"49907-zemrit-za-zivot" },
  "50423": { t:"Río Escondido",                                 d:"Emilio Fernández",                       c:"Mexiko",                            y:1948, r:110, s:"NAV",  b:"classic", syn:"Klasika mexického režiséra Emilia Fernándeze.",                                                                                  u:"50423-rio-escondido" },
  "50596": { t:"Sexy bestie",                                   d:"Jonathan Glazer",                        c:"VB, ES, USA",                       y:2000, r:89,  s:"NAV",  b:"classic", syn:"Gangsterský film Jonathana Glazera (Sexy Beast).",                                                                               u:"50596-sexy-bestie" },
  "49695": { t:"Duch v cele",                                   d:"Joko Anwar",                             c:"Indonésie, Jižní Korea",            y:2026, r:107, s:"POZ",  b:"night",   syn:"",                                                                                                                              u:"49695-duch-vcele" },
  "49240": { t:"Šeptej",                                        d:"David Ondříček",                         c:"ČR",                                y:1996, r:85,  s:"ZUC",  b:"classic", syn:"Raný film Davida Ondříčka.",                                                                                                     u:"49240-septej" },
  "50149": { t:"Vtáčkovia, siroty a blázni",                    d:"Juraj Jakubisko",                        c:"Československo, FR",                y:1969, r:78,  s:"NAV",  b:"classic", syn:"Surreální klasika Juraje Jakubiska.",                                                                                            u:"50149-vtackovia-siroty-ablazni" },
  "50668": { t:"Zavraždění čínského bookmakera",                d:"John Cassavetes",                        c:"USA",                               y:1978, r:109, s:"ZUC",  b:"classic", syn:"Klasika Johna Cassavetese.",                                                                                                     u:"50668-zavrazdeni-cinskeho-bookmakera" },
  "50682": { t:"Věrná kopie",                                   d:"Abbas Kiarostami",                       c:"FR, IT, BE, Írán",                  y:2010, r:106, s:"POC",  b:"classic", syn:"Film Abbáse Kiarostamího s Juliette Binoche.",                                                                                   u:"50682-verna-kopie" },
  "48427": { t:"Olivia",                                        d:"Sofía Petersen",                         c:"Argentina, VB, ES",                 y:2025, r:127, s:"IMA",  b:"cine",    syn:"",                                                                                                                              u:"48427-olivia" },
  "50196": { t:"Magnát",                                        d:"Charlotte Zhang",                        c:"Kanada, USA",                       y:2025, r:89,  s:"IMA",  b:"cine",    syn:"",                                                                                                                              u:"50196-magnat" },
  "48857": { t:"Naše země",                                     d:"Lucrecia Martel",                        c:"AR, USA, MX, FR, NL, DK",           y:2025, r:124, s:"HOR",  b:"must",    syn:"Nový film Lucrecie Martel.",                                                                                                     u:"48857-nase-zeme" },
  "49685": { t:"Příběh dokumentárního filmu – Osmdesátky",      d:"Mark Cousins",                           c:"Velká Británie",                    y:2026, r:120, s:"ZU",   b:"cine",    syn:"Filmová esej Marka Cousinse (Příběh filmu: Odysea).",                                                                           u:"49685-pribeh-dokumentarniho-filmu-osmdesatky" },
  "49703": { t:"Dvě hory tíží moji hruď",                       d:"Viv Li",                                 c:"Německo, Nizozemsko",               y:2026, r:86,  s:"HOR",  b:"",        syn:"",                                                                                                                              u:"49703-dve-hory-tizi-moji-hrud" },
  "50652": { t:"Naše spása",                                    d:"Emmanuel Marre",                         c:"Francie, Belgie",                   y:2026, r:158, s:"HOR",  b:"cine",    syn:"",                                                                                                                              u:"50652-nase-spasa" },
  "50536": { t:"Zde je dům mého přítele",                       d:"Maryam Ataei, Hossein Keshavarz",        c:"Írán, USA",                         y:2025, r:96,  s:"ZU",   b:"",        syn:"",                                                                                                                              u:"50536-zde-je-dum-meho-pritele" },
  "50660": { t:"Stanice",                                       d:"Sara Ishaq",                             c:"Jemen, JO, FR, DE…",                y:2026, r:113, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"50660-stanice" },
  "50630": { t:"Nechť Bůh odpouští všem",                       d:"Pierfrancesco Diliberto (PIF)",          c:"Itálie",                            y:2026, r:115, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"50630-necht-buh-odpousti-vsem" },
  "49679": { t:"V neznámých vodách",                            d:"Lance Hammer",                           c:"VB, USA",                           y:2026, r:122, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"49679-v-neznamych-vodach" },
  "48523": { t:"Bára Basiková",                                 d:"Helena Třeštíková",                      c:"ČR",                                y:2026, r:98,  s:"ZU",   b:"cine",    syn:"Časosběrný dokument Heleny Třeštíkové o zpěvačce.",                                                                              u:"48523-bara-basikova" },
  "50594": { t:"Babí léto",                                     d:"Vladimír Michálek",                      c:"ČR",                                y:2001, r:98,  s:"ZUC",  b:"classic", syn:"",                                                                                                                              u:"50594-babi-leto" },
  "50629": { t:"Spolužáci",                                     d:"Umberto Carteni",                        c:"Itálie",                            y:2026, r:97,  s:"HOR",  b:"",        syn:"",                                                                                                                              u:"50629-spoluzaci" },
  "50662": { t:"Život ženy",                                    d:"Charline Bourgeois-Tacquet",             c:"Francie, Belgie",                   y:2026, r:98,  s:"HOR",  b:"",        syn:"",                                                                                                                              u:"50662-zivot-zeny" },
  "50657": { t:"Cantona",                                       d:"David Tryhorn, Ben Nicholas",            c:"Velká Británie",                    y:2026, r:116, s:"HOR",  b:"",        syn:"Dokument o fotbalové ikoně Ericu Cantonovi.",                                                                                    u:"50657-cantona" },
  "50428": { t:"Lissy",                                         d:"Konrad Wolf",                            c:"Německo",                           y:1957, r:89,  s:"NAV",  b:"classic", syn:"",                                                                                                                              u:"50428-lissy" },
  "50421": { t:"Otázka života a smrti",                         d:"Michael Powell, Emeric Pressburger",     c:"Velká Británie",                    y:1946, r:105, s:"NAV",  b:"classic", syn:"Klasika dvojice Powell–Pressburger; ve Varech poprvé 1947.",                                                                     u:"50421-otazka-zivota-asmrti" },
  "50681": { t:"Tři barvy: Modrá",                              d:"Krzysztof Kieślowski",                   c:"FR, PL, CH",                        y:1993, r:98,  s:"POC",  b:"classic", syn:"První díl trilogie Krzysztofa Kieślowského.",                                                                                   u:"50681-tri-barvy-modra" },
  "50708": { t:"Basquiat",                                      d:"Julian Schnabel",                        c:"USA",                               y:1996, r:107, s:"POC",  b:"classic", syn:"Životopisné drama o malíři J.-M. Basquiatovi.",                                                                                 u:"50708-basquiat" },
  "49689": { t:"Rose",                                          d:"Markus Schleinzer",                      c:"Rakousko, Německo",                 y:2026, r:94,  s:"HOR",  b:"",        syn:"",                                                                                                                              u:"49689-rose" },
  "49945": { t:"Poslední vrchol",                               d:"Amir Bar-Lev",                           c:"USA",                               y:2026, r:98,  s:"HOR",  b:"",        syn:"",                                                                                                                              u:"49945-posledni-vrchol" },
  "50535": { t:"Rodinný film",                                  d:"Kevin Bacon",                            c:"USA",                               y:2026, r:87,  s:"POZ",  b:"night",   syn:"Režijní počin Kevina Bacona.",                                                                                                  u:"50535-rodinny-film" },
  "50431": { t:"Krvavá země",                                   d:"Vasilis Georgiadis",                     c:"Řecko",                             y:1965, r:124, s:"NAV",  b:"classic", syn:"",                                                                                                                              u:"50431-krvava-zeme" },
  "50645": { t:"Bdící oči",                                     d:"Rakan Mayasi",                           c:"BE, LB, PS, QA, SA",                y:2026, r:101, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"50645-bdici-oci" },
  "49359": { t:"Filipiñana",                                    d:"Rafael Manuel",                          c:"SG, VB, PH, FR",                    y:2026, r:101, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"49359-filipiana" },
  "49691": { t:"AnyMart",                                       d:"Yusuke Iwasaki",                         c:"Japonsko",                          y:2025, r:89,  s:"POZ",  b:"night",   syn:"",                                                                                                                              u:"49691-anymart" },
  "50427": { t:"Děti Hirošimy",                                 d:"Kaneto Shindō",                          c:"Japonsko",                          y:1954, r:97,  s:"NAV",  b:"classic", syn:"Klasické japonské drama o následcích atomové bomby.",                                                                            u:"50427-deti-hirosimy" },
  "50132": { t:"Horký pramen",                                  d:"Ramzi Bashour",                          c:"USA",                               y:2026, r:98,  s:"HOR",  b:"",        syn:"",                                                                                                                              u:"50132-horky-pramen" },
  "49213": { t:"Rozbřesky",                                     d:"Rhayne Vermette",                        c:"Kanada",                            y:2025, r:93,  s:"IMA",  b:"cine",    syn:"",                                                                                                                              u:"49213-rozbresky" },
  "49274": { t:"Podoby milostného vztahu ke světu",             d:"Jakub Kučera",                           c:"ČR",                                y:2026, r:71,  s:"IMA",  b:"cine",    syn:"",                                                                                                                              u:"49274-podoby-milostneho-vztahu-kesvetu" },
  "48719": { t:"Souffleur",                                     d:"Gastón Solnicki",                        c:"Rakousko, Argentina",               y:2025, r:78,  s:"HOR",  b:"cine",    syn:"",                                                                                                                              u:"48719-souffleur" },
  "49941": { t:"Vyvolený",                                      d:"Tomasz Mielnik",                         c:"ČR, PL, RO",                        y:2026, r:90,  s:"ZU",   b:"",        syn:"",                                                                                                                              u:"49941-vyvoleny" },
  "48467": { t:"Růže z Nevady",                                 d:"Mark Jenkin",                            c:"Velká Británie",                    y:2025, r:115, s:"IMA",  b:"cine",    syn:"Od Marka Jenkina (Bait). Natočeno na 16mm.",                                                                                    u:"48467-ruze-znevady" },
  "49696": { t:"Rozvod za časů války",                          d:"Andrius Blaževičius",                    c:"LT, LU, IE, ČR",                    y:2026, r:109, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"49696-rozvod-za-casu-valky" },
  "49418": { t:"Drž mě",                                        d:"Myrsini Aristidou",                      c:"CY, GR, DK, USA",                   y:2026, r:103, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"49418-drz-me" },
  "49425": { t:"Hanba a peníze",                                d:"Visar Morina",                           c:"DE, XK, SI, AL, MK, BE",            y:2026, r:130, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"49425-hanba-apenize" },
  "50643": { t:"Sloni v mlze",                                  d:"Abinash Bikram Shah",                    c:"Nepál, FR, BR, DE, NO",             y:2026, r:108, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"50643-sloni-vmlze" },
  "50547": { t:"Fena",                                          d:"Dominga Sotomayor",                      c:"Chile, Brazílie",                   y:2026, r:111, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"50547-fena" },
  "50603": { t:"Ať žije Carmen!",                               d:"Sébastien Laudenbach",                   c:"Francie, Lucembursko",              y:2026, r:90,  s:"HOR",  b:"",        syn:"Animovaný film.",                                                                                                               u:"50603-at-zije-carmen" },
  "50636": { t:"Zbabělec",                                      d:"Lukas Dhont",                            c:"Belgie, FR, NL",                    y:2026, r:120, s:"HOR",  b:"must",    syn:"Nový film Lukase Dhonta (Blízko / Close).",                                                                                     u:"50636-zbabelec" },
  "49684": { t:"Mouchy",                                        d:"Fernando Eimbcke",                       c:"Mexiko, Španělsko",                 y:2026, r:103, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"49684-mouchy" },
  "49704": { t:"Papája",                                        d:"Priscilla Kellen",                       c:"Brazílie",                          y:2026, r:75,  s:"HOR",  b:"",        syn:"",                                                                                                                              u:"49704-papaja" },
  "50667": { t:"Znenadání",                                     d:"Ryûsuke Hamaguchi",                      c:"FR, JP, DE, BE",                    y:2026, r:196, s:"HOR",  b:"must",    syn:"Nový film Rjúsukeho Hamaguchiho (Drive My Car). Dlouhých 196 min.",                                                             u:"50667-znenadani" },
  "49688": { t:"Poslední kapsář v New Yorku",                   d:"Noah Segan",                             c:"USA",                               y:2026, r:88,  s:"HOR",  b:"",        syn:"",                                                                                                                              u:"49688-posledni-kapsar-v-new-yorku" },
  "50655": { t:"Není míru pod olivami",                         d:"Giuseppe De Santis",                     c:"Itálie",                            y:1950, r:104, s:"NAV",  b:"classic", syn:"",                                                                                                                              u:"50655-neni-miru-pod-olivami" },
  "50627": { t:"Trainspotting",                                 d:"Danny Boyle",                            c:"Velká Británie",                    y:1996, r:94,  s:"NAV",  b:"classic", syn:"Kultovní film Dannyho Boylea.",                                                                                                  u:"50627-trainspotting" },
  "49673": { t:"Dao",                                           d:"Alain Gomis",                            c:"Francie, Senegal, GW",              y:2026, r:185, s:"HOR",  b:"cine",    syn:"",                                                                                                                              u:"49673-dao" },
  "50418": { t:"Poslední příležitost",                          d:"Leopold Lindtberg",                      c:"Švýcarsko",                         y:1945, r:112, s:"NAV",  b:"classic", syn:"",                                                                                                                              u:"50418-posledni-prilezitost" },
  "50654": { t:"Ben'Imana",                                     d:"Marie-Clémentine Dusabejambo",           c:"Rwanda, GA, FR, NO, CI",            y:2026, r:102, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"50654-benimana" },
  "49700": { t:"Světelný sloup",                                d:"Xu Zao",                                 c:"Čína",                              y:2026, r:90,  s:"HOR",  b:"",        syn:"",                                                                                                                              u:"49700-svetelny-sloup" },
  "48416": { t:"Vzpomínka",                                     d:"Vladlena Sandu",                         c:"Francie, Nizozemsko",               y:2025, r:98,  s:"HOR",  b:"",        syn:"",                                                                                                                              u:"48416-vzpominka" },
  "50692": { t:"Milovaný",                                      d:"Rodrigo Sorogoyen",                      c:"Španělsko",                         y:2026, r:135, s:"HOR",  b:"must",    syn:"Nový film Rodriga Sorogoyena (Bestie).",                                                                                         u:"50692-milovany" },
  "48415": { t:"Kopytem sem, kopytem tam",                      d:"Věra Chytilová",                         c:"Československo",                    y:1988, r:134, s:"ZUC",  b:"classic", syn:"Film Věry Chytilové.",                                                                                                           u:"48415-kopytem-sem-kopytem-tam" },
  "50653": { t:"Muž, kterého miluji",                           d:"Ira Sachs",                              c:"USA",                               y:2026, r:95,  s:"HOR",  b:"",        syn:"",                                                                                                                              u:"50653-muz-ktereho-miluji" },
  "50644": { t:"Jsme jedné krve",                               d:"Valentina Maurel",                       c:"Belgie, FR, MX",                    y:2026, r:108, s:"HOR",  b:"",        syn:"",                                                                                                                              u:"50644-jsme-jedne-krve" },
  // pásma krátkých filmů
  "ps1":  { t:"Pragueshorts I",                   d:"pásmo krátkých filmů", c:"—", y:2026, r:90,  s:"KRAT", b:"", syn:"Soutěžní pásmo krátkých filmů.",          u:"" },
  "ps2":  { t:"Pragueshorts II",                  d:"pásmo krátkých filmů", c:"—", y:2026, r:90,  s:"KRAT", b:"", syn:"Soutěžní pásmo krátkých filmů.",          u:"" },
  "psd":  { t:"Pragueshorts – Dětské filmy",      d:"pásmo krátkých filmů", c:"—", y:2026, r:75,  s:"KRAT", b:"", syn:"Pásmo krátkých filmů pro děti.",          u:"" },
  "ima1": { t:"Imagina – krátké filmy I",         d:"pásmo krátkých filmů", c:"—", y:2026, r:90,  s:"KRAT", b:"", syn:"Pásmo experimentálních krátkých filmů.",  u:"" },
  "ima2": { t:"Imagina – krátké filmy II",        d:"pásmo krátkých filmů", c:"—", y:2026, r:90,  s:"KRAT", b:"", syn:"Pásmo experimentálních krátkých filmů.",  u:"" },
};

// [den, kód, čas, sál, filmId, diskuse?]
export const SCR = [
  // 8.7
  [8,"611","08:30","T1","50433"],[8,"614","11:00","T1","49480"],[8,"615","14:00","T1","50666"],[8,"616","17:00","T1","49965"],[8,"618","20:00","T1","50526"],[8,"61A","23:00","T1","49702"],
  [8,"621","09:00","T2","50659"],[8,"622","12:00","T2","50601",1],[8,"623","15:00","T2","49309",1],[8,"626","18:00","T2","50599",1],[8,"627","20:30","T2","49676",1],[8,"62A","24:00","T2","50602"],
  [8,"633","13:00","T3","50262"],[8,"634","16:00","T3","49760"],[8,"636","19:00","T3","50430"],[8,"637","21:00","T3","50426"],
  [8,"651","09:00","T4","50357"],[8,"652","11:30","T4","49419"],[8,"654","14:00","T4","49467"],[8,"656","17:00","T4","50432"],[8,"658","20:00","T4","48448"],[8,"659","22:00","T4","49697"],
  [8,"6C1","09:00","CAS","49680"],[8,"6C2","12:00","CAS","49183",1],[8,"6C3","15:00","CAS","49047",1],[8,"6C5","18:00","CAS","ima2",1],[8,"6C8","21:00","CAS","49174",1],[8,"6C9","24:00","CAS","50633"],
  [8,"6D1","10:00","MD","50337"],[8,"6D2","13:00","MD","50111"],[8,"6D3","16:00","MD","50065"],[8,"6D4","19:00","MD","50038"],[8,"6D5","22:00","MD","50663"],
  [8,"6H1","10:30","HUS","48447"],[8,"6H3","13:30","HUS","50647"],[8,"6H5","16:30","HUS","50435"],[8,"6H6","19:30","HUS","49670"],[8,"6H9","21:30","HUS","48920"],
  [8,"6K1","09:00","DRA","50429"],[8,"6K3","11:30","DRA","50637"],[8,"6K6","15:00","DRA","ps2",1],[8,"6K9","18:00","DRA","50646",1],[8,"6KA","21:00","DRA","50323"],
  [8,"6L1","10:00","L3","50509"],[8,"6L2","13:00","L3","48780"],[8,"6L3","16:00","L3","50251"],[8,"6L4","19:00","L3","49934"],[8,"6L5","22:00","L3","50651"],
  [8,"6P1","10:00","PUPP","49871",1],[8,"6P2","13:00","PUPP","50402",1],[8,"6P3","16:00","PUPP","50600",1],[8,"6P5","19:00","PUPP","49310",1],[8,"6P6","22:00","PUPP","50656"],
  // 9.7
  [9,"711","08:30","T1","50635"],[9,"713","10:30","T1","50664"],[9,"715","14:00","T1","50683"],[9,"716","17:00","T1","50528"],[9,"717","19:30","T1","50539"],[9,"719","22:30","T1","50634"],
  [9,"721","09:00","T2","50513"],[9,"722","12:00","T2","49480",1],[9,"723","15:00","T2","50453",1],[9,"726","18:00","T2","49592",1],[9,"727","20:30","T2","50641"],[9,"72A","24:00","T2","49683"],
  [9,"733","13:00","T3","50251"],[9,"734","16:00","T3","49934"],[9,"736","19:00","T3","49309",1],[9,"737","21:00","T3","50532"],
  [9,"751","09:00","T4","49844"],[9,"752","11:30","T4","50509"],[9,"754","14:00","T4","48780"],[9,"756","17:00","T4","49907"],
  [9,"7C1","09:00","CAS","50423"],[9,"7C2","12:00","CAS","50065",1],[9,"7C3","15:00","CAS","50038",1],[9,"7C5","18:00","CAS","50646",1],[9,"7C8","21:00","CAS","50596"],[9,"7C9","24:00","CAS","49695"],
  [9,"7D1","10:00","MD","49310"],[9,"7D2","13:00","MD","49240"],[9,"7D3","16:00","MD","50149"],[9,"7D4","19:00","MD","50668"],[9,"7D5","22:00","MD","50682"],
  [9,"7H1","10:30","HUS","48427"],[9,"7H3","13:30","HUS","ps2",1],[9,"7H5","16:30","HUS","50196",1],[9,"7H6","19:30","HUS","ima2",1],[9,"7HA","22:30","HUS","50428"],
  [9,"7K1","09:00","DRA","48857"],[9,"7K4","12:00","DRA","49685"],[9,"7K6","15:00","DRA","49703"],[9,"7K8","17:00","DRA","50652"],[9,"7KA","21:00","DRA","50536",1],
  [9,"7L1","10:00","L3","49183"],[9,"7L2","13:00","L3","49047"],[9,"7L3","16:00","L3","49871"],[9,"7L4","19:00","L3","50402"],[9,"7L5","22:00","L3","50660"],
  [9,"7P1","10:00","PUPP","49965",1],[9,"7P2","13:00","PUPP","50526",1],[9,"7P3","16:00","PUPP","50630",1],[9,"7P5","19:00","PUPP","49679"],
  [9,"7S1","10:00","CIS","48523"],[9,"7S2","13:00","CIS","50594"],[9,"7S3","16:00","CIS","50629"],[9,"7S4","19:00","CIS","50662"],[9,"7S5","22:00","CIS","50657"],
  // 10.7
  [10,"811","08:30","T1","50421"],[10,"814","11:00","T1","50681"],[10,"815","14:00","T1","50708"],[10,"816","17:00","T1","49689"],[10,"817","19:30","T1","49945"],[10,"819","22:30","T1","50535"],
  [10,"821","09:00","T2","50431"],[10,"822","12:00","T2","50645"],[10,"823","15:00","T2","49359"],[10,"825","17:30","T2","50637"],[10,"828","21:00","T2","50323"],[10,"82A","24:00","T2","50602"],
  [10,"831","08:30","T3","50337"],[10,"832","10:30","T3","49480"],[10,"833","13:00","T3","49871"],[10,"834","16:00","T3","50402"],[10,"836","19:00","T3","50630",1],[10,"838","22:00","T3","49691"],
  [10,"851","09:00","T4","ps1"],[10,"852","11:30","T4","49183"],[10,"854","14:00","T4","49047"],[10,"856","17:00","T4","50111"],[10,"858","20:00","T4","49418"],[10,"859","22:00","T4","49425"],
  [10,"8C1","09:00","CAS","50643"],[10,"8C2","12:00","CAS","50453",1],[10,"8C3","15:00","CAS","49592",1],[10,"8C4","17:30","CAS","50652"],[10,"8C8","21:00","CAS","50547"],[10,"8C9","24:00","CAS","49702"],
  [10,"8D1","10:00","MD","50603"],[10,"8D2","13:00","MD","50426"],[10,"8D3","16:00","MD","50636"],[10,"8D4","19:00","MD","50427"],[10,"8D5","22:00","MD","50132"],
  [10,"8H1","10:30","HUS","49213"],[10,"8H3","13:30","HUS","psd"],[10,"8H5","16:30","HUS","ima1"],[10,"8H6","19:30","HUS","49274"],[10,"8H8","21:00","HUS","48719"],
  [10,"8K1","09:00","DRA","50599"],[10,"8K2","10:30","DRA","49941"],[10,"8K5","12:30","DRA","48467"],[10,"8K7","15:30","DRA","50433"],[10,"8K9","18:00","DRA","49696"],[10,"8KA","21:00","DRA","50600"],
  [10,"8L1","10:00","L3","50065"],[10,"8L2","13:00","L3","50038"],[10,"8L3","16:00","L3","49965"],[10,"8L4","19:00","L3","50526"],[10,"8L5","22:00","L3","49685"],
  [10,"8P1","10:00","PUPP","50528",1],[10,"8P2","13:00","PUPP","50539",1],[10,"8P5","19:00","PUPP","49684"],[10,"8P6","22:00","PUPP","50656"],
  // 11.7
  [11,"921","09:00","T2","49704"],[11,"922","12:00","T2","50668"],[11,"924","16:30","T2","50667"],[11,"928","21:00","T2","49688"],[11,"92A","24:00","T2","50535"],
  [11,"931","08:30","T3","50526"],[11,"932","10:30","T3","49965"],[11,"933","13:00","T3","50528"],[11,"934","16:00","T3","50539"],[11,"936","19:00","T3","48523"],[11,"938","22:00","T3","50666"],
  [11,"951","09:00","T4","50600"],[11,"952","11:30","T4","50065"],[11,"954","14:00","T4","50038"],[11,"956","17:00","T4","50453"],[11,"958","20:00","T4","49592"],[11,"959","22:00","T4","50629"],
  [11,"9C1","09:00","CAS","50111"],[11,"9C2","12:00","CAS","50636"],[11,"9C3","15:00","CAS","50664"],[11,"9C5","18:00","CAS","50653"],[11,"9C7","20:30","CAS","49673"],[11,"9C9","24:00","CAS","49683"],
  [11,"9D1","10:00","MD","50418"],[11,"9D2","13:00","MD","50513"],[11,"9D3","16:00","MD","50655"],[11,"9D4","19:00","MD","50635"],[11,"9D5","22:00","MD","50627"],
  [11,"9H1","10:30","HUS","49309"],[11,"9H2","12:00","HUS","49680"],[11,"9H4","14:00","HUS","50599"],[11,"9H5","16:30","HUS","50654"],[11,"9H6","19:30","HUS","50423"],[11,"9HA","22:30","HUS","49700"],
  [11,"9K1","09:00","DRA","49907"],[11,"9K4","12:00","DRA","50357"],[11,"9K6","15:00","DRA","49310"],[11,"9K9","18:00","DRA","48416"],[11,"9KA","21:00","DRA","50337"],
  [11,"9L1","10:00","L3","50453"],[11,"9L2","13:00","L3","49592"],[11,"9L3","16:00","L3","50528"],[11,"9L4","19:00","L3","50539"],[11,"9L5","22:00","L3","50644"],
  [11,"9S1","10:00","CIS","50601"],[11,"9S2","13:00","CIS","50692"],[11,"9S3","16:00","CIS","48415"],[11,"9S4","19:00","CIS","50663"],[11,"9S5","22:00","CIS","50651"],
].map(([day, code, t, v, f, disc]) => ({ id:`${day}-${code}`, day, code, t, v, f, disc:!!disc }));

export const DAYS = [
  { d:8,  label:"St 8. 7."  },
  { d:9,  label:"Čt 9. 7."  },
  { d:10, label:"Pá 10. 7." },
  { d:11, label:"So 11. 7." },
];

export const TIME_GROUPS = [
  { label:"Dopoledne", from:0,    to:720      },
  { label:"Odpoledne", from:720,  to:1080     },
  { label:"Večer",     from:1080, to:1320     },
  { label:"Noc",       from:1320, to:Infinity },
];
